/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly "/user": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get user profile
         * @description Retrieves the authenticated user's profile information
         */
        readonly get: operations["getUserProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/user/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get user statistics
         * @description Retrieves account-wide statistics for the authenticated user
         */
        readonly get: operations["getUserStats"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/collections": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get all collections
         * @description Retrieves all collections for the authenticated user
         */
        readonly get: operations["getAllCollections"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/collections/childrens": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get all child collections
         * @description Retrieves child collections for the authenticated user
         */
        readonly get: operations["getChildCollections"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/collection": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create a new collection
         * @description Creates a new collection with the specified properties
         */
        readonly post: operations["createCollection"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/collection/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get collection details
         * @description Retrieves detailed information about a specific collection
         */
        readonly get: operations["getCollection"];
        /**
         * Update a collection
         * @description Updates properties of an existing collection
         */
        readonly put: operations["updateCollection"];
        readonly post?: never;
        /**
         * Delete a collection
         * @description Permanently deletes a collection and all its bookmarks
         */
        readonly delete: operations["deleteCollection"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/collection/-99": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Permanently empty current Trash
         * @description Deletes all items currently in Trash; the MCP v3 tool requires explicit confirmation
         */
        readonly delete: operations["emptyTrash"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/raindrops/{collectionId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get bookmarks from a collection
         * @description Retrieves bookmarks from a specific collection with filtering options
         */
        readonly get: operations["getBookmarksByCollection"];
        /**
         * Update multiple bookmarks in a collection
         * @description Update properties of multiple bookmarks in a specific collection at once
         */
        readonly put: operations["batchUpdateBookmarksInCollection"];
        readonly post?: never;
        /**
         * Delete multiple bookmarks or empty collection
         * @description Delete multiple bookmarks in a specific collection or empty trash/collection
         */
        readonly delete: operations["batchDeleteBookmarksInCollection"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/raindrop": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Add a new bookmark
         * @description Creates a new bookmark with automatic metadata extraction
         */
        readonly post: operations["createBookmark"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/raindrop/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get bookmark by ID
         * @description Retrieves detailed information about a specific bookmark
         */
        readonly get: operations["getBookmark"];
        /**
         * Update a bookmark
         * @description Updates properties of an existing bookmark
         */
        readonly put: operations["updateBookmark"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/raindrop/suggest": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Suggest tags and collections for a new URL */
        readonly post: operations["suggestForUrl"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/raindrop/{id}/suggest": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Suggest tags and collections for an existing bookmark */
        readonly get: operations["suggestForBookmark"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/highlights": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get all highlights
         * @description Retrieves all highlights from a user's bookmarks with pagination
         */
        readonly get: operations["getAllHighlights"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/highlights/{collectionId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get all highlights in a collection
         * @description Retrieves all highlights from bookmarks in a specific collection
         */
        readonly get: operations["getHighlightsByCollection"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tags": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get all tags used in bookmarks
         * @description Retrieves all unique tags used in the user's bookmarks
         */
        readonly get: operations["getAllTags"];
        /**
         * Rename or merge tags globally
         * @description Rename or merge tags across all collections
         */
        readonly put: operations["renameOrMergeAllTagsV3"];
        readonly post?: never;
        /**
         * Delete multiple tags globally
         * @description Delete multiple tags from all bookmarks
         */
        readonly delete: operations["deleteAllTagsV3"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tags/{collectionId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get tags from a specific collection
         * @description Retrieves all tags used in bookmarks within a specific collection
         */
        readonly get: operations["getTagsByCollection"];
        /**
         * Rename or merge tags in a collection
         * @description Rename or merge tags within a specific collection
         */
        readonly put: operations["renameOrMergeCollectionTags"];
        readonly post?: never;
        /**
         * Delete tags from a collection
         * @description Delete multiple tags from bookmarks in a specific collection
         */
        readonly delete: operations["deleteCollectionTags"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        readonly Collection: {
            /** @description Collection ID */
            readonly _id: number;
            /** @description Collection title */
            readonly title: string;
            /** @description Collection description */
            readonly description?: string;
            /** @description Collection color theme */
            readonly color?: string;
            /** @description Number of bookmarks in collection */
            readonly count?: number;
            /** @description Whether collection is public */
            readonly public?: boolean;
            /** @description Parent collection reference */
            readonly parent?: {
                readonly $id?: number;
            };
            /** @description Whether collection is expanded in UI */
            readonly expanded?: boolean;
            /** @description Sort order within parent */
            readonly sort?: string;
            /** @description Access control settings */
            readonly access?: Record<string, never>;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            readonly created?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            readonly lastUpdate?: string;
        };
        readonly Bookmark: {
            /** @description Bookmark ID */
            readonly _id: number;
            /**
             * Format: uri
             * @description Bookmark URL
             */
            readonly link: string;
            /** @description Bookmark title */
            readonly title: string;
            /** @description Bookmark description/excerpt */
            readonly excerpt?: string;
            /** @description User notes for the bookmark */
            readonly note?: string;
            /**
             * @description Type of bookmark content
             * @enum {string}
             */
            readonly type?: "link" | "article" | "image" | "video" | "document" | "audio";
            /**
             * Format: uri
             * @description Cover image URL
             */
            readonly cover?: string;
            /** @description Array of tags */
            readonly tags?: readonly string[];
            /** @description Whether bookmark is marked as important */
            readonly important?: boolean;
            /** @description Reminder settings */
            readonly reminder?: {
                /** Format: date-time */
                readonly date?: string;
                readonly note?: string;
            };
            /** @description Whether bookmark is in trash */
            readonly removed?: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            readonly created?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            readonly lastUpdate?: string;
            /** @description Domain of the bookmark URL */
            readonly domain?: string;
            /** @description User ID of creator */
            readonly creatorRef?: number;
            /** @description Collection reference */
            readonly collection?: {
                readonly $id?: number;
                readonly title?: string;
            };
            /** @description Text highlights for this bookmark */
            readonly highlights?: readonly components["schemas"]["Highlight"][];
            /** @description List of media/covers associated with the raindrop */
            readonly media?: readonly {
                /** Format: uri */
                readonly link?: string;
            }[];
            /** @description Details about the permanent copy (cached version) */
            readonly cache?: {
                /** @enum {string} */
                readonly status?: "ready" | "retry" | "failed";
                readonly size?: number;
                /** Format: date-time */
                readonly created?: string;
            };
        };
        readonly Highlight: {
            /** @description Unique highlight ID */
            readonly _id: string;
            /** @description Highlighted text content */
            readonly text: string;
            /** @description Optional note for the highlight */
            readonly note?: string;
            /**
             * @description Highlight color
             * @default yellow
             * @enum {string}
             */
            readonly color: "blue" | "brown" | "cyan" | "gray" | "green" | "indigo" | "orange" | "pink" | "purple" | "red" | "teal" | "yellow";
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            readonly created?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            readonly lastUpdate?: string;
            /** @description Title of the parent bookmark */
            readonly title?: string;
            /**
             * Format: uri
             * @description URL of the parent bookmark
             */
            readonly link?: string;
            /** @description Domain of the parent bookmark */
            readonly domain?: string;
            /** @description Context around the highlight */
            readonly excerpt?: string;
            /** @description Tags from the parent bookmark */
            readonly tags?: readonly string[];
            /** @description Reference to parent bookmark */
            readonly raindrop?: {
                readonly _id?: number;
                readonly title?: string;
                readonly link?: string;
                readonly collection?: {
                    readonly $id?: number;
                };
            };
        };
        readonly Tag: {
            /** @description Tag name */
            readonly _id: string;
            /** @description Number of bookmarks with this tag */
            readonly count: number;
        };
        readonly User: {
            /** @description User ID */
            readonly _id: number;
            /**
             * Format: email
             * @description User email address
             */
            readonly email: string;
            /** @description User's full name */
            readonly fullName?: string;
            /**
             * Format: uri
             * @description Avatar image URL
             */
            readonly avatar?: string;
            /** @description Whether user has Pro subscription */
            readonly pro?: boolean;
            /**
             * Format: date-time
             * @description Pro subscription expiration date
             */
            readonly proExpire?: string;
            /**
             * Format: date-time
             * @description Registration date
             */
            readonly registered?: string;
            /**
             * Format: date-time
             * @description Last profile update
             */
            readonly lastUpdate?: string;
        };
        readonly CreateCollectionRequest: {
            /** @description Collection title */
            readonly title: string;
            /** @description Whether collection should be public */
            readonly public?: boolean;
            /** @description Parent collection reference */
            readonly parent?: {
                readonly $id?: number;
            };
            /** @description Collection color theme */
            readonly color?: string;
            /** @description Collection description */
            readonly description?: string;
        };
        readonly UpdateCollectionRequest: {
            /** @description Collection title */
            readonly title?: string;
            /** @description Whether collection should be public */
            readonly public?: boolean;
            /** @description Parent collection reference */
            readonly parent?: {
                readonly $id?: number;
            };
            /** @description Collection color theme */
            readonly color?: string;
            /** @description Collection description */
            readonly description?: string;
        };
        readonly ShareCollectionRequest: {
            /**
             * @description Sharing permission level
             * @enum {string}
             */
            readonly level: "view" | "edit" | "remove";
            /** @description Email addresses to share with */
            readonly emails?: readonly string[];
        };
        readonly CreateBookmarkRequest: {
            /**
             * Format: uri
             * @description Bookmark URL
             */
            readonly link: string;
            /** @description Bookmark title (auto-extracted if not provided) */
            readonly title?: string;
            /** @description Bookmark description */
            readonly excerpt?: string;
            /** @description User notes for the bookmark */
            readonly note?: string;
            /** @description Array of tags */
            readonly tags?: readonly string[];
            /** @description Whether bookmark is important */
            readonly important?: boolean;
            /** @description Target collection reference */
            readonly collection?: {
                readonly $id?: number;
            };
            /** @description Settings for content parsing */
            readonly pleaseParse?: Record<string, never>;
        };
        readonly UpdateBookmarkRequest: {
            /**
             * Format: uri
             * @description Bookmark URL
             */
            readonly link?: string;
            /** @description Bookmark title */
            readonly title?: string;
            /** @description Bookmark description */
            readonly excerpt?: string;
            /** @description User notes */
            readonly note?: string;
            /** @description Array of tags */
            readonly tags?: readonly string[];
            /** @description Whether bookmark is important */
            readonly important?: boolean;
            /** @description Target collection reference */
            readonly collection?: {
                readonly $id?: number;
            };
            /** @description One-element v3 highlight mutation payload */
            readonly highlights?: readonly {
                readonly _id?: string;
                readonly text?: string;
                readonly note?: string;
                /** @enum {string} */
                readonly color?: "blue" | "brown" | "cyan" | "gray" | "green" | "indigo" | "orange" | "pink" | "purple" | "red" | "teal" | "yellow";
            }[];
            /**
             * Format: uri
             * @description Cover image URL
             */
            readonly cover?: string;
        };
        readonly BatchUpdateBookmarksRequest: {
            /** @description Array of bookmark IDs to update */
            readonly ids: readonly number[];
            /** @description Tags to set on bookmarks */
            readonly tags?: readonly string[];
            /** @description Collection to move bookmarks to */
            readonly collection?: {
                readonly $id?: number;
            };
            /** @description Whether bookmarks should be marked important */
            readonly important?: boolean;
            /** @description Whether bookmarks should be marked as broken */
            readonly broken?: boolean;
        };
        readonly BulkMoveBookmarksRequest: {
            /** @description Array of bookmark IDs to move */
            readonly ids: readonly number[];
            /** @description Target collection */
            readonly collection: {
                readonly $id?: number;
            };
        };
        readonly BatchTagBookmarksRequest: {
            /** @description Array of bookmark IDs */
            readonly ids: readonly number[];
            /** @description Tags to add or remove */
            readonly tags: readonly string[];
            /**
             * @description Whether to replace existing tags or add to them
             * @default false
             */
            readonly replace: boolean;
        };
        readonly SetReminderRequest: {
            /**
             * Format: date-time
             * @description Reminder date and time
             */
            readonly date: string;
            /** @description Optional reminder note */
            readonly note?: string;
        };
        readonly CreateHighlightRequest: {
            /** @description Bookmark reference */
            readonly raindrop: {
                readonly $id?: number;
            };
            /** @description Highlighted text */
            readonly text: string;
            /** @description Optional note for the highlight */
            readonly note?: string;
            /**
             * @description Highlight color
             * @default yellow
             * @enum {string}
             */
            readonly color: "blue" | "brown" | "cyan" | "gray" | "green" | "indigo" | "orange" | "pink" | "purple" | "red" | "teal" | "yellow";
        };
        readonly UpdateHighlightRequest: {
            /** @description Updated highlight text */
            readonly text?: string;
            /** @description Updated note */
            readonly note?: string;
            /**
             * @description Updated highlight color
             * @enum {string}
             */
            readonly color?: "blue" | "brown" | "cyan" | "gray" | "green" | "indigo" | "orange" | "pink" | "purple" | "red" | "teal" | "yellow";
        };
        readonly TagOperationRequest: {
            /** @description Original tag name (for rename operation) */
            readonly from?: string;
            /** @description New tag name */
            readonly to?: string;
            /** @description Array of tag names (for merge operation) */
            readonly tags?: readonly string[];
        };
        readonly ImportBookmarksRequest: {
            /**
             * Format: binary
             * @description Bookmarks file to import
             */
            readonly file: string;
            /** @description Collection ID to import into */
            readonly collection?: string;
            /**
             * @description Format of the import file
             * @enum {string}
             */
            readonly format?: "html" | "csv" | "pocket" | "instapaper" | "netscape" | "readwise";
            /**
             * @description Import mode
             * @default add
             * @enum {string}
             */
            readonly mode: "add" | "replace";
            /**
             * @description Whether to parse content during import
             * @default true
             */
            readonly parse: boolean;
        };
        readonly ImportFromUrlRequest: {
            /**
             * Format: uri
             * @description URL of bookmarks file to import
             */
            readonly url: string;
            /**
             * @description Whether to parse imported bookmarks
             * @default true
             */
            readonly parse: boolean;
            /** @description Collection details to import into */
            readonly collection?: {
                readonly $id?: number;
                readonly title?: string;
            };
        };
        readonly ExportBookmarksRequest: {
            /** @description Collection ID to export (omit for all bookmarks) */
            readonly collection?: number;
            /**
             * @description Export format
             * @enum {string}
             */
            readonly format: "csv" | "html" | "pdf";
            /**
             * @description Include broken bookmarks
             * @default false
             */
            readonly broken: boolean;
            /**
             * @description Include duplicate bookmarks
             * @default false
             */
            readonly duplicates: boolean;
        };
        readonly UserProfileResponse: {
            readonly result: boolean;
            readonly user: components["schemas"]["User"];
        };
        readonly UserStatsResponse: {
            readonly result: boolean;
            readonly items?: readonly {
                readonly _id?: number;
                readonly count?: number;
            }[];
            readonly meta?: {
                readonly broken?: {
                    readonly count?: number;
                };
            };
            readonly stats?: {
                readonly bookmarks?: number;
                readonly collections?: number;
                readonly highlights?: number;
                readonly tags?: number;
                readonly trash?: number;
            };
        };
        readonly CollectionStatsResponse: {
            readonly result: boolean;
            readonly stats: {
                readonly bookmarks?: number;
                readonly highlights?: number;
                readonly tags?: number;
            };
        };
        readonly CollectionsResponse: {
            readonly result: boolean;
            readonly items: readonly components["schemas"]["Collection"][];
        };
        readonly CollectionItemResponse: {
            readonly result: boolean;
            readonly item: components["schemas"]["Collection"];
        };
        readonly ShareCollectionResponse: {
            readonly result: boolean;
            /**
             * Format: uri
             * @description Public sharing link
             */
            readonly link: string;
            /** @description List of users with access */
            readonly access: readonly {
                /** Format: email */
                readonly email?: string;
                /** @enum {string} */
                readonly level?: "view" | "edit";
            }[];
        };
        readonly BookmarksResponse: {
            readonly result: boolean;
            readonly items: readonly components["schemas"]["Bookmark"][];
            /** @description Total number of matching bookmarks */
            readonly count?: number;
            /** @description Collection ID that was searched */
            readonly collectionId?: number;
        };
        readonly BookmarkItemResponse: {
            readonly result: boolean;
            readonly item: components["schemas"]["Bookmark"];
        };
        readonly HighlightsResponse: {
            readonly result: boolean;
            readonly items: readonly components["schemas"]["Highlight"][];
            /** @description Total matching highlights if supplied by upstream */
            readonly count?: number;
        };
        readonly HighlightItemResponse: {
            readonly result: boolean;
            readonly item: components["schemas"]["Highlight"];
        };
        readonly TagsResponse: {
            readonly result: boolean;
            readonly items: readonly components["schemas"]["Tag"][];
        };
        readonly SuggestionsResponse: {
            readonly result: boolean;
            readonly item: {
                readonly tags?: readonly string[];
                readonly collections?: readonly {
                    readonly _id?: number;
                    readonly title?: string;
                }[];
                readonly covers?: readonly string[];
            };
        };
        readonly ImportResponse: {
            readonly result: boolean;
            readonly items: readonly {
                readonly _id?: number;
                readonly link?: string;
            }[];
            /** @description Number of bookmarks imported */
            readonly imported?: number;
            /** @description Number of duplicates found */
            readonly duplicates?: number;
        };
        readonly ImportJobResponse: {
            readonly result: boolean;
            readonly item: {
                /** @description Import job ID */
                readonly _id?: string;
            };
        };
        readonly ImportStatusResponse: {
            readonly result: boolean;
            /**
             * @description Current import status
             * @enum {string}
             */
            readonly status: "in-progress" | "ready" | "error";
            /** @description Import progress percentage */
            readonly progress?: number;
            /** @description Number of bookmarks imported so far */
            readonly imported?: number;
            /** @description Number of duplicates found */
            readonly duplicates?: number;
            /** @description Error message if status is 'error' */
            readonly error?: string;
        };
        readonly ExportResponse: {
            readonly result: boolean;
            /**
             * Format: uri
             * @description Download URL for the exported file
             */
            readonly url: string;
        };
        readonly ExportStatusResponse: {
            readonly result: boolean;
            /**
             * @description Current export status
             * @enum {string}
             */
            readonly status: "in-progress" | "ready" | "error";
            /** @description Export progress percentage */
            readonly progress?: number;
            /**
             * Format: uri
             * @description Download URL when ready
             */
            readonly url?: string;
            /** @description Error message if status is 'error' */
            readonly error?: string;
        };
        readonly FiltersResponse: {
            readonly result: boolean;
            /** @description Available tag filters */
            readonly tags: readonly string[];
            /** @description Available domain filters */
            readonly domains: readonly string[];
            /** @description Available highlight filters */
            readonly highlights: readonly string[];
        };
        readonly ResultResponse: {
            /** @description Whether the operation was successful */
            readonly result: boolean;
            /** @description Optional upstream batch modification count */
            readonly modified?: number;
        };
        readonly ErrorResponse: {
            /** @default false */
            readonly result: boolean;
            /** @description Error message */
            readonly error: string;
            /** @description Detailed error description */
            readonly errorMessage?: string;
            /** @description Error code */
            readonly errorCode?: number;
        };
    };
    responses: {
        /** @description Bad request - invalid parameters or request body */
        readonly BadRequestError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized - invalid or missing access token */
        readonly UnauthorizedError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        readonly NotFoundError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        readonly RateLimitError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        readonly ServerError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Collection ID */
        readonly CollectionId: number;
        /** @description Bookmark ID */
        readonly BookmarkId: number;
        /** @description Search query for filtering results */
        readonly SearchQuery: string;
        /** @description Sort order for results */
        readonly SortOrder: "-created" | "created" | "score" | "-sort" | "title" | "-title" | "domain" | "-domain";
        /** @description Filter by specific tag */
        readonly TagFilter: string;
        /** @description Filter by important flag */
        readonly ImportantFilter: boolean;
        /** @description Filter by duplicates */
        readonly DuplicatesFilter: boolean;
        /** @description Filter by broken links */
        readonly BrokenFilter: boolean;
        /** @description Filter by items without tags */
        readonly NotagFilter: boolean;
        /** @description Filter by presence of highlights */
        readonly HighlightFilter: boolean;
        /** @description Filter by domain */
        readonly DomainFilter: string;
        /** @description Filter by collection ID */
        readonly CollectionFilter: number;
        /** @description Number of items per page */
        readonly PerPage: number;
        /** @description Page number for pagination */
        readonly Page: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    readonly getUserProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description User profile retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            readonly 401: components["responses"]["UnauthorizedError"];
            readonly 429: components["responses"]["RateLimitError"];
            readonly 500: components["responses"]["ServerError"];
        };
    };
    readonly getUserStats: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description User statistics retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserStatsResponse"];
                };
            };
            readonly 401: components["responses"]["UnauthorizedError"];
        };
    };
    readonly getAllCollections: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Collections retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CollectionsResponse"];
                };
            };
            readonly 401: components["responses"]["UnauthorizedError"];
        };
    };
    readonly getChildCollections: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Child collections retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CollectionsResponse"];
                };
            };
            readonly 401: components["responses"]["UnauthorizedError"];
        };
    };
    readonly createCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        readonly responses: {
            /** @description Collection created successfully */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CollectionItemResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequestError"];
            readonly 401: components["responses"]["UnauthorizedError"];
        };
    };
    readonly getCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly id: components["parameters"]["CollectionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Collection retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CollectionItemResponse"];
                };
            };
            readonly 404: components["responses"]["NotFoundError"];
        };
    };
    readonly updateCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly id: components["parameters"]["CollectionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateCollectionRequest"];
            };
        };
        readonly responses: {
            /** @description Collection updated successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CollectionItemResponse"];
                };
            };
        };
    };
    readonly deleteCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly id: components["parameters"]["CollectionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Collection deleted successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
            readonly 404: components["responses"]["NotFoundError"];
        };
    };
    readonly emptyTrash: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Trash emptied successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
            readonly 401: components["responses"]["UnauthorizedError"];
        };
    };
    readonly getBookmarksByCollection: {
        readonly parameters: {
            readonly query?: {
                /** @description Search query for filtering results */
                readonly search?: components["parameters"]["SearchQuery"];
                /** @description Sort order for results */
                readonly sort?: components["parameters"]["SortOrder"];
                /** @description Number of items per page */
                readonly perpage?: components["parameters"]["PerPage"];
                /** @description Page number for pagination */
                readonly page?: components["parameters"]["Page"];
                /** @description Include nested collections */
                readonly nested?: boolean;
            };
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Bookmarks retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["BookmarksResponse"];
                };
            };
        };
    };
    readonly batchUpdateBookmarksInCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["BatchUpdateBookmarksRequest"];
            };
        };
        readonly responses: {
            /** @description Bookmarks updated successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    readonly batchDeleteBookmarksInCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": {
                    /** @description Array of bookmark IDs to delete */
                    readonly ids?: readonly number[];
                };
            };
        };
        readonly responses: {
            /** @description Bookmarks deleted successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    readonly createBookmark: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateBookmarkRequest"];
            };
        };
        readonly responses: {
            /** @description Bookmark created successfully */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["BookmarkItemResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequestError"];
        };
    };
    readonly getBookmark: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Bookmark ID */
                readonly id: components["parameters"]["BookmarkId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Bookmark retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["BookmarkItemResponse"];
                };
            };
            readonly 404: components["responses"]["NotFoundError"];
        };
    };
    readonly updateBookmark: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Bookmark ID */
                readonly id: components["parameters"]["BookmarkId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateBookmarkRequest"];
            };
        };
        readonly responses: {
            /** @description Bookmark updated successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["BookmarkItemResponse"];
                };
            };
        };
    };
    readonly suggestForUrl: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": {
                    /** Format: uri */
                    readonly link: string;
                };
            };
        };
        readonly responses: {
            /** @description Suggestions retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
        };
    };
    readonly suggestForBookmark: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Suggestions retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
        };
    };
    readonly getAllHighlights: {
        readonly parameters: {
            readonly query?: {
                /** @description Page number for pagination */
                readonly page?: components["parameters"]["Page"];
                /** @description Number of highlights per page (max 50) */
                readonly perpage?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Highlights retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HighlightsResponse"];
                };
            };
        };
    };
    readonly getHighlightsByCollection: {
        readonly parameters: {
            readonly query?: {
                /** @description Page number for pagination */
                readonly page?: components["parameters"]["Page"];
                /** @description Number of highlights per page (max 50) */
                readonly perpage?: number;
            };
            readonly header?: never;
            readonly path: {
                /** @description Collection ID */
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Collection highlights retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HighlightsResponse"];
                };
            };
        };
    };
    readonly getAllTags: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Tags retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
    readonly renameOrMergeAllTagsV3: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TagOperationRequest"];
            };
        };
        readonly responses: {
            /** @description Tag operation completed successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    readonly deleteAllTagsV3: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    /** @description Array of tag names to delete */
                    readonly tags: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description Tags deleted successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    readonly getTagsByCollection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Collection tags retrieved successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
    readonly renameOrMergeCollectionTags: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TagOperationRequest"];
            };
        };
        readonly responses: {
            /** @description Tag operation completed successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    readonly deleteCollectionTags: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly collectionId: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    /** @description Array of tag names to delete */
                    readonly tags: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description Tags deleted successfully */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
}
