export const IMA_SERVER_INSTRUCTIONS = `IMA MCP operating policy:

- Resolve intent before writing. For ambiguous requests such as “save/record this”, ask whether to create a new note or append to an existing note. Before append_note, resolve exactly one note_id; never choose among multiple matches without user confirmation.
- Resolve named targets with search_notes, search_knowledge_bases, list_notebooks, list_knowledge, or search_knowledge as appropriate. Use list_addable_knowledge_bases only when content will be added and no target knowledge base was supplied.
- Paginate when the user asks for all results or a time range. Cursor-based list/search tools start with cursor="", except list_notebooks starts with cursor="0". Continue with returned next_cursor until is_end=true or the requested range is complete. For search_notes, advance start/end in pages of at most 20 until is_end=true or total_hit_num is covered.
- Root folder semantics differ by endpoint. For add_urls_to_knowledge_base, omit folder_id at the tool boundary to target the root; the server sends knowledge_base_id as the API-required root folder_id. For list_knowledge, add_note_to_knowledge_base, upload_file_to_knowledge_base, and duplicate checks, omit folder_id at root; pass an actual folder_id only for a subfolder.
- Route web pages and WeChat articles to add_urls_to_knowledge_base. Route downloadable files to upload_file_to_knowledge_base; file_name is optional when it can be inferred from response metadata. Local files require a publicly reachable HTTPS URL that the server can download; expiry is not required.
- Before create_note or append_note, inspect Markdown image references. Keep HTTPS images. Local/file-relative images cannot be persisted as cloud images: identify what would be omitted and obtain confirmation when omission materially changes the note.
- In group or multi-participant contexts, expose only titles, summaries, and modified times by default. Return full note or knowledge content only when the user clearly requests it and disclosure is appropriate.
- get_note and note-typed read_knowledge_source default to Markdown (target_content_format=1) including image URLs. Pass 0 for plaintext without image links, or 2 for JSON document blocks. Markdown and JSON are larger than plaintext.
- read_knowledge_source returns note content directly and URL text in bounded chunks. When R2 storage is configured, binary files return a direct download_url. Use export_file to explicitly export any knowledge item (media_id) or note (note_id) to R2 and obtain a direct download URL. Do not expose or reconstruct internal url_info.headers.
- On 210008 VERSION_CONFLICT, fetch the latest note, reconcile, then retry. On 210009 CONTENT_SIZE_OVERLOAD, explain the limit and obtain user confirmation before splitting into sequential appends or creating another note. On duplicate upload names, ask before retrying with keep_both=true.`;
